import { krProgress, okrProgress, krStatus, okrStatus, timeElapsedPct } from "../okr.js";
let pass=0,fail=0;
const eq=(n,g,w)=>{const ok=JSON.stringify(g)===JSON.stringify(w);console.log((ok?"PASS  ":"FAIL  ")+n);ok?pass++:(fail++,console.log("   want",JSON.stringify(w),"got",JSON.stringify(g)))};
const near=(n,g,w,t=0.01)=>{const ok=g!==null&&Math.abs(g-w)<t;console.log((ok?"PASS  ":"FAIL  ")+n);ok?pass++:(fail++,console.log("   want",w,"got",g))};
near("Iberian 59->63, at 61 is halfway", krProgress({baseline:59,target:63,current_value:61}),50);
near("on the baseline is 0%, not 94%", krProgress({baseline:59,target:63,current_value:59}),0);
near("reaching target is 100%", krProgress({baseline:59,target:63,current_value:63}),100);
near("overshoot reads above 100", krProgress({baseline:59,target:63,current_value:65}),150);
near("Canada -8 -> 0, at -4", krProgress({baseline:-8,target:0,current_value:-4}),50);
near("reduce 42 -> 35, at 38.5", krProgress({baseline:42,target:35,current_value:38.5}),50);
eq("target equal to baseline is unscoreable", krProgress({baseline:77,target:77,current_value:77}),null);
eq("unscoreable KR skipped in the mean", okrProgress([{baseline:0,target:10,current_value:5},{baseline:5,target:5,current_value:5}]),50);
eq("nothing scoreable is null", okrProgress([{baseline:5,target:5,current_value:5}]),null);
near("OKR progress is the mean", okrProgress([{baseline:0,target:10,current_value:2},{baseline:0,target:10,current_value:4},{baseline:0,target:10,current_value:9}]),50);
eq("manual override wins", krStatus({baseline:0,target:10,current_value:0,status_override:"green"}),"green");
const kr=(c,m,d)=>({baseline:0,target:100,current_value:c,created_at:m,due_date:d});
const JAN='2026-01-01',DEC='2026-12-31';
eq("20% done in February is on track", krStatus(kr(20,JAN,DEC),new Date('2026-02-20')),"green");
eq("20% done in December is off track", krStatus(kr(20,JAN,DEC),new Date('2026-12-01')),"red");
eq("55% at halfway is on track", krStatus(kr(55,JAN,DEC),new Date('2026-07-02')),"green");
eq("30% at halfway is at risk", krStatus(kr(30,JAN,DEC),new Date('2026-07-02')),"amber");
eq("no due date falls back to progress", krStatus({baseline:0,target:10,current_value:8}),"green");
eq("no due date means no pace", timeElapsedPct({created_at:JAN}),null);
eq("an OKR is as weak as its worst KR", okrStatus([kr(90,JAN,DEC),kr(5,JAN,DEC)],new Date('2026-12-01')),"red");
eq("all healthy stays green", okrStatus([kr(90,JAN,DEC),kr(95,JAN,DEC)],new Date('2026-06-01')),"green");
console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail?1:0);
